version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./seeds/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  server:
    build: .
    env_file:
      - .env
    ports:
      - "8088:8088"
    restart: always
volumes:
  database_data:
